### ISSUE TITLE
Newlines not working for %img?

### ISSUE THREAD

**Issue by md3sum** [jessemiller/HamlPy#52] opened 2011-11-23 13:26 UTC
Hi, 
I noticed that you can separate long dictionary values for a tag like %script. I tried that, and it worked.
But if I try to do this: 

```
%div{'class': 'row'}
    %img{'src': '/static/imgs/ibl_logo.gif', 
        'alt': 'IBL Logo'}
    %br
```

It does not work and second line, i.e. **'alt'** tag prints on a second line. I have tried different ways to see if it could work but I am lost at it and hence decided to file it as a bug. If it is not, my apologies.

**Comment by jessemiller** [comment] 2011-12-01 04:30
I just committed a test that uses your code there and I think it outputs the right stuff. If you check out the code, take a look under `hamlpy/test/templates` you will see two files `multiLineDict.hamlpy` and `multiLineDict.html`. Running `nosetests template_compare_test.py` from the test directory should pass, confirming they are the same.

If that doesn't actually test the problem you're having, could you try to recreate the problem in the test and let me know and I don't mind fixing it up. Thanks!

**Comment by bcoughlan** [comment] 2011-12-01 19:52
Tested this out in my own environment and can't reproduce

**Comment by bigdrum** [comment] 2011-12-15 08:48
But this is broken:

``` haml
%div{'class': 'row'}
    %img{'src': '/static/imgs/ibl_logo_{{id}}.gif', 
        'alt': 'IBL Logo'}
    %br
```

**Comment by bcoughlan** [comment] 2011-12-16 00:05
Hmmmm ok, I've narrowed it down to this:

Start of elements.py

```
MULTILINE_ATTR_ELEMENT_REGEX = re.compile(r"""
(?P<tag>%\w+(\:\w+)?)?
(?P<id>\#[\w-]*)?
(?P<class>\.[\w\.-]*)*
(?P<attribute_start>\{[^\}]+$)
""", re.X)
```

As you can see towards the end (after attribute_start) this regex is looking for an opening `{` without a closing `}`. The regex should ignore brackets in single or double quotes, (which is why cooyeah's example doesn't work).

I don't see an easy way to solve this problem with regular expressions, can anyone else?

If not, I'll rewrite it not to use regular expressions.

**Comment by bigdrum** [comment] 2011-12-16 04:59
This is a quick hack:

``` python
M = re.compile(r"""
(?P<tag>%\w+(\:\w+)?)?
(?P<id>\#[\w-]*)?
(?P<class>\.[\w\.-]*)*
(?P<attribute_start>\{([^\}]|\{\{[^\{\}]+\}\}|\#\{[^\{\}]+\})*$)
""", re.X)
```

But I would ++1 for not using regex to do the parsing.

**Comment by bcoughlan** [comment] 2011-12-16 15:23
Another problem caused by that regex occurs with Javascript/CSS. That regex doesn't match `document.ready(function() {` but does match `document.ready(function() { x=2` which could cause problems.

I have a non-regex solution almost working, the trouble is how do differentiate between CSS and HAML, e.g. the CSS `.myclass {` is both valid CSS and a valid multi-line HAML string. I think the easiest way is to check if it's inside a `:css` filter, but then that could cause problems with the regular `<link rel` CSS tags.

Any thoughts?

**Comment by bcoughlan** [comment] 2011-12-16 17:36
OK, I've made a fix on my fork. All the tests pass and both examples above work as expected but I'd like a second opinion before writing tests and making a pull request.

I've used `isinstance` to exclude text inside filter nodes. Although it's "considered harmful" (ahem), I don't see the harm in this case

My main concerns are that the errors produced from missing braces will be unintelligible and that simply excluding filter nodes isn't sufficient.

**Comment by bcoughlan** [comment] 2011-12-17 04:58
Sorry for the accidental commits, can't seem to figure out how to undo them :/

**Comment by bcoughlan** [comment] 2011-12-19 22:43
Going to delete my repository and recommit, sorry to those who will get a blast of emails!

**Comment by md3sum** [comment] 2011-12-20 20:24
Hi, 
I did notice that regex as being a source of problems too but I am currently not using the github synced code.
I use pip install hamlpy to get my packages. 
Would you be able to commit the latest version to pypi so it could be upgraded using the pip commands if its not too much to ask for? :)
Thank you.
M

**Comment by bcoughlan** [comment] 2011-12-30 04:47
Hi md3sum,

If you have easy_install, `easy_install hamlpy` pulls directly from the github repo. When/if Jesse approves the pull request I made you should be able to get the changes that way.

Barry

**Comment by md3sum** [comment] 2012-01-05 11:36
I ran a pip install upgrade hamlpy but it said there was nothing to update since version 0.4 
I assume I have to wait :)

**Comment by jessemiller** [comment] 2012-01-06 00:41
Should be merged and updated in PyPi. Sorry for the delay.. startup life and all that..

**Comment by md3sum** [comment] 2012-01-06 08:24
No worries Jesse. I have sent another pull request for #58. Let us know when you get around to it. :)

**Closed as completed** 2012-02-07 04:25 UTC
